
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NEQ_OP = 55;
  public static final int ASSIGN_OP = 42;
  public static final int SEQ = 24;
  public static final int FORALL = 34;
  public static final int STRING_LITERAL = 15;
  public static final int LT_OP = 52;
  public static final int MULT_OP = 45;
  public static final int CHAR_LITERAL = 14;
  public static final int LPAREN = 3;
  public static final int SEMI = 2;
  public static final int RPAREN = 4;
  public static final int DOT_OP = 57;
  public static final int TYPE = 25;
  public static final int TDEF = 37;
  public static final int COMMA = 11;
  public static final int FI = 32;
  public static final int IN_OP = 56;
  public static final int OR_OP = 50;
  public static final int NEG_FLOAT_LITERAL = 20;
  public static final int MAIN = 40;
  public static final int IF = 29;
  public static final int AND_OP = 49;
  public static final int EOF = 0;
  public static final int NOT_OP = 48;
  public static final int OD = 36;
  public static final int RETURN = 26;
  public static final int error = 1;
  public static final int CONCAT_OP = 12;
  public static final int IMPL_OP = 51;
  public static final int FDEF = 38;
  public static final int IDENT = 13;
  public static final int PLUS_OP = 43;
  public static final int RATIONAL_LITERAL = 21;
  public static final int MINUS_OP = 44;
  public static final int LBRACK = 7;
  public static final int COLON = 10;
  public static final int DICT = 23;
  public static final int LBRACE = 5;
  public static final int ELSE = 31;
  public static final int EQ_OP = 54;
  public static final int NEG_RATIONAL_LITERAL = 22;
  public static final int READ = 28;
  public static final int RBRACK = 8;
  public static final int POW_OP = 47;
  public static final int WHILE = 33;
  public static final int DIV_OP = 46;
  public static final int RANGLE = 9;
  public static final int THEN = 30;
  public static final int RBRACE = 6;
  public static final int LEN = 41;
  public static final int ALIAS = 39;
  public static final int FLOAT_LITERAL = 19;
  public static final int LTE_OP = 53;
  public static final int DO = 35;
  public static final int PRINT = 27;
  public static final int BOOL_LITERAL = 16;
  public static final int NEG_INT_LITERAL = 18;
  public static final int INT_LITERAL = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "RANGLE",
  "COLON",
  "COMMA",
  "CONCAT_OP",
  "IDENT",
  "CHAR_LITERAL",
  "STRING_LITERAL",
  "BOOL_LITERAL",
  "INT_LITERAL",
  "NEG_INT_LITERAL",
  "FLOAT_LITERAL",
  "NEG_FLOAT_LITERAL",
  "RATIONAL_LITERAL",
  "NEG_RATIONAL_LITERAL",
  "DICT",
  "SEQ",
  "TYPE",
  "RETURN",
  "PRINT",
  "READ",
  "IF",
  "THEN",
  "ELSE",
  "FI",
  "WHILE",
  "FORALL",
  "DO",
  "OD",
  "TDEF",
  "FDEF",
  "ALIAS",
  "MAIN",
  "LEN",
  "ASSIGN_OP",
  "PLUS_OP",
  "MINUS_OP",
  "MULT_OP",
  "DIV_OP",
  "POW_OP",
  "NOT_OP",
  "AND_OP",
  "OR_OP",
  "IMPL_OP",
  "LT_OP",
  "LTE_OP",
  "EQ_OP",
  "NEQ_OP",
  "IN_OP",
  "DOT_OP"
  };
}

